<?php

$sql = "UPDATE `historial_clinico` SET 
`est_civil` = '" . $_POST['est_civil'] . "', 
`ocupacion` = '" . $_POST['ocupacion'] . "', 
`heredo_familiares` = '" . $_POST['heredo_familiares'] . "', 
`vivienda` = '" . $_POST['vivienda'] . "',
`lugar_excretas` = '" . $_POST['lugar_excretas'] . "',
`anim_domesticos` = '" . $_POST['anim_domesticos'] . "',
`agua_ingesta` = '" . $_POST['agua_ingesta'] . "',
`habitos_higienicos` = '" . $_POST['habitos_higienicos'] . "',
`escolaridad` = '" . $_POST['escolaridad'] . "',
`tiempo_libre` = '" . $_POST['tiempo_libre'] . "',
`act_fisica` = '" . $_POST['act_fisica'] . "',
`patron_sueno` = '" . $_POST['patron_sueno'] . "',
`notasuno` = '" . $_POST['notasuno'] . "',
`alergias` = '" . $_POST['alergias'] . "',
`transfusiones` = '" . $_POST['transfusiones'] . "',
`quirurgicos` = '" . $_POST['quirurgicos'] . "',
`congenitos` = '" . $_POST['congenitos'] . "',
`traumaticos` = '" . $_POST['traumaticos'] . "',
`enfe_crondegenerativa` = '" . $_POST['enfe_crondegenerativa'] . "',
`enfe_infecciosas` = '" . $_POST['enfe_infecciosas'] . "',
`enfe_exantematicas` = '" . $_POST['enfe_exantematicas'] . "',
`otras_patologias` = '" . $_POST['otras_patologias'] . "',
`padecimiento_act` = '" . $_POST['padecimiento_act'] . "',
`circulatorio` = '" . $_POST['circulatorio'] . "',
`digestivo` = '" . $_POST['digestivo'] . "',
`endocrino` = '" . $_POST['endocrino'] . "',
`inmunologico` = '" . $_POST['inmunologico'] . "',
`linfatico` = '" . $_POST['linfatico'] . "',
`muscular` = '" . $_POST['muscular'] . "',
`nervioso` = '" . $_POST['nervioso'] . "',
`oseo` = '" . $_POST['oseo'] . "',
`reproductor` = '" . $_POST['reproductor'] . "',
`respiratorio` = '" . $_POST['respiratorio'] . "',
`urinario` = '" . $_POST['urinario'] . "',
`cardiovascular` = '" . $_POST['cardiovascular'] . "',
`notasdos` = '" . $_POST['notasdos'] . "',
`habitus_ext` = '" . $_POST['habitus_ext'] . "',
`paciente` = '" . $_POST['paciente'] . "',
`signos_vitales` = '" . $_POST['signos_vitales'] . "',
`temperatura` = '" . $_POST['temperatura'] . "',
`peso` = '" . $_POST['peso'] . "',
`tension_arterial` = '" . $_POST['tension_arterial'] . "',
`altura` = '" . $_POST['altura'] . "',
`frec_cardiaca` = '" . $_POST['frec_cardiaca'] . "',
`frec_respiratoria` = '" . $_POST['frec_respiratoria'] . "',
`masa_muscular` = '" . $_POST['masa_muscular'] . "',
`cabeza` = '" . $_POST['cabeza'] . "',
`cuello` = '" . $_POST['cuello'] . "',
`torax` = '" . $_POST['torax'] . "',
`abdomen` = '" . $_POST['abdomen'] . "',
`miembros` = '" . $_POST['miembros'] . "',
`genitales` = '" . $_POST['genitales'] . "',
`piel_anexos` = '" . $_POST['piel_anexos'] . "',
`resultados_lab` = '" . $_POST['resultados_lab'] . "',
`gabinete` = '" . $_POST['gabinete'] . "',
`histopatologia` = '" . $_POST['histopatologia'] . "',
`otros` = '" . $_POST['otros'] . "',
`diag_probclinicos` = '" . $_POST['diag_probclinicos'] . "',
`pronostico` = '" . $_POST['pronostico'] . "',
`indic_terapeutica` = '" . $_POST['indic_terapeutica'] . "',
`notastres` = '" . $_POST['notastres'] . "'
WHERE `historial_clinico`.`id` = '" . $_GET['id'] . "'";



$conn->query($sql);

echo " <br> HISTORIAL CLINICO ACTUALZIADO correctamente <br>"; 