<?php

$sql = "INSERT INTO `historial_clinico` (`id`, `user_id`, `est_civil`, 
`ocupacion`, `heredo_familiares`, `vivienda`, `lugar_excretas`, `anim_domesticos`, 
`agua_ingesta`, `habitos_higienicos`, `escolaridad`, `tiempo_libre`, `act_fisica`, 
`patron_sueno`, `notasuno`, `alergias`, `transfusiones`, `quirurgicos`, 
`congenitos`, `traumaticos`, `enfe_crondegenerativa`, `enfe_infecciosas`, 
`enfe_exantematicas`, `otras_patologias`, `padecimiento_act`, `circulatorio`, 
`digestivo`, `endocrino`, `inmunologico`, `linfatico`, `muscular`, `nervioso`, 
`oseo`, `reproductor`, `respiratorio`, `urinario`, `cardiovascular`, `notasdos`, 
`habitus_ext`, `paciente`, `signos_vitales`, `temperatura`, `peso`, 
`tension_arterial`, `altura`, `frec_cardiaca`, `frec_respiratoria`, 
`masa_muscular`, `cabeza`, `cuello`, `torax`, `abdomen`, `miembros`, 
`genitales`, `piel_anexos`, `resultados_lab`, `gabinete`, `histopatologia`, 
`otros`, `diag_probclinicos`, `pronostico`, `indic_terapeutica`, `notastres`, 
`created_at`) VALUES 
(NULL, '" . $_POST['user_id'] ."', '" . $_POST['est_civil'] ."', 
'" . $_POST['ocupacion'] ."', '" . $_POST['heredo_familiares'] ."', 
'" . $_POST['vivienda'] ."', '" . $_POST['lugar_excretas'] ."', 
'" . $_POST['anim_domesticos'] ."', '" . $_POST['agua_ingesta'] ."', 
'" . $_POST['habitos_higienicos'] ."', '" . $_POST['escolaridad'] ."', 
'" . $_POST['tiempo_libre'] ."', '" . $_POST['act_fisica'] ."', 
'" . $_POST['patron_sueno'] ."', '" . $_POST['notasuno'] ."', 
'" . $_POST['alergias'] ."', '" . $_POST['transfusiones'] ."', 
'" . $_POST['quirurgicos'] ."', '" . $_POST['congenitos'] ."', 
'" . $_POST['traumaticos'] ."', '" . $_POST['enfe_crondegenerativa'] ."', 
'" . $_POST['enfe_infecciosas'] ."', '" . $_POST['enfe_exantematicas'] ."', 
'" . $_POST['otras_patologias'] ."', '" . $_POST['padecimiento_act'] ."', 
'" . $_POST['circulatorio'] ."', '" . $_POST['digestivo'] ."', 
'" . $_POST['endocrino'] ."', '" . $_POST['inmunologico'] ."', 
'" . $_POST['linfatico'] ."', '" . $_POST['muscular'] ."', 
'" . $_POST['nervioso'] ."', '" . $_POST['oseo'] ."', 
'" . $_POST['reproductor'] ."', '" . $_POST['respiratorio'] ."', 
'" . $_POST['urinario'] ."', '" . $_POST['cardiovascular'] ."', 
'" . $_POST['notasdos'] ."', '" . $_POST['habitus_ext'] ."', 
'" . $_POST['paciente'] ."', '" . $_POST['signos_vitales'] ."', 
'" . $_POST['temperatura'] ."', '" . $_POST['peso'] ."', 
'" . $_POST['tension_arterial'] ."', '" . $_POST['altura'] ."', 
'" . $_POST['frec_cardiaca'] ."', '" . $_POST['frec_respiratoria'] ."', 
'" . $_POST['masa_muscular'] ."', '" . $_POST['cabeza'] ."', 
'" . $_POST['cuello'] ."', '" . $_POST['torax'] ."', 
'" . $_POST['abdomen'] ."', '" . $_POST['miembros'] ."', 
'" . $_POST['genitales'] ."', '" . $_POST['piel_anexos'] ."', 
'" . $_POST['resultados_lab'] ."', '" . $_POST['gabinete'] ."', 
'" . $_POST['histopatologia'] ."', '" . $_POST['otros'] ."', 
'" . $_POST['diag_probclinicos'] ."', '" . $_POST['pronostico'] ."', 
'" . $_POST['indic_terapeutica'] ."', '" . $_POST['notastres'] ."', 
CURRENT_TIMESTAMP)";

$conn->query($sql);

echo "HISTORIAL CLINICO CREADO <BR>";